### ISSUE TITLE
collection._immutable() dropped?

### ISSUE THREAD

**Issue by strikeout** [gliesesoftware/mylar#3]
Hi!

Whats the rationale behind dropping the `collection._immutable` field declaration?

**Comment by ramijarrar** [comment]
The immutable annotation is not documented in the codebase of the mylar prototype or mentioned in the paper's description of the API (Figure 2). 

From what I can tell by looking at it's implementation (mylar-principal package) it is used to compute MACs, but the paper states (section 4.5) that MACs are computed over the specified authentication set and so it should suffice to use the auth_set annotation alone.

This seems to be supported by the silencing of all errors associated with removing immutable when the auth_set annotation is used.
