### ISSUE TITLE
Declaration of MylarCol[name] necessary even for non-mylar collections

### ISSUE THREAD

**Issue by strikeout** [gliesesoftware/mylar#4]
Right now it seems to be necessary to add every collection (even the collections with no encryped fields) to the `MylarCol` global register, else we get an `self === undefined`  in `connection.constructor.prototype.registerStore`.

**Comment by gliesedev** [comment]
The MylarCol dictionary felt like a hack from the start. 

It has now been depreciated (as of v0.3.0) in favour of a more elegant solution for retrieving collection instances that requires no user input.
